import React from 'react';
import { ScrollText, AlertTriangle, Copyright, Scale } from 'lucide-react';

const TermsOfService: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto text-gray-700 dark:text-gray-300 space-y-8 animate-in fade-in duration-500">
      <div className="border-b border-gray-200 dark:border-gray-800 pb-8">
        <h1 className="text-3xl md:text-4xl font-display font-bold text-gray-900 dark:text-white mb-4">Terms of Service</h1>
        <p className="text-gray-500 dark:text-gray-400">Effective Date: {new Date().toLocaleDateString()}</p>
      </div>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <ScrollText size={20} className="text-accent-600 dark:text-accent-400"/> Service Agreement
        </h2>
        <p>
          By accessing and using Quintin's Virtual Dressing Room ("the Service"), you agree to be bound by these Terms. 
          If you disagree with any part of the terms, you may not access the Service.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <AlertTriangle size={20} className="text-accent-600 dark:text-accent-400"/> Acceptable Use & Conduct
        </h2>
        <p>
          You represent and warrant that you own all rights to the images you upload or have obtained explicit permission from the rights holder.
          You agree NOT to use the Service to:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-gray-600 dark:text-gray-400">
            <li>Upload content that is illegal, harmful, threatening, abusive, defamatory, or invasive of another's privacy.</li>
            <li>Generate non-consensual deepfake imagery or sexual content.</li>
            <li>Infringe upon the intellectual property rights of others.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <Copyright size={20} className="text-accent-600 dark:text-accent-400"/> Intellectual Property
        </h2>
        <p>
           You retain all ownership rights to the original content you upload. The Service does not claim ownership of your photos.
           However, you understand that the output is generated by Artificial Intelligence and may not be copyrightable in certain jurisdictions.
        </p>
      </section>
      
      <section className="space-y-4">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
             <Scale size={20} className="text-accent-600 dark:text-accent-400"/> AI Disclaimer
          </h2>
          <p>
              This Service uses generative AI to simulate clothing fit. The results are artistic approximations and may not accurately reflect 
              real-world sizing, fabric drape, or color. We are not liable for any purchasing decisions made based on these visualizations.
          </p>
          <div className="bg-red-50 dark:bg-red-900/10 border border-red-200 dark:border-red-500/20 p-4 rounded-lg mt-4">
              <p className="text-sm text-red-600 dark:text-red-200">
                  THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED.
              </p>
          </div>
      </section>
    </div>
  );
};

export default TermsOfService;